=== antonialoytorrens-DAW2018-2020/bodegaxml/factures.dtd
<!ELEMENT celler (productes, clients, factures)>
  <!ELEMENT productes (producte)+>
    <!ELEMENT producte (#PCDATA)>
      <!ATTLIST producte id ID #REQUIRED>
      <!ATTLIST producte preu CDATA #REQUIRED>
  <!ELEMENT clients (client)+>
    <!ELEMENT client (nom, llinatges, contacte)>
      <!ATTLIST client id ID #REQUIRED>
      <!ELEMENT nom (#PCDATA)>
      <!ELEMENT llinatges (#PCDATA)>
      <!ELEMENT contacte (mobil | fix)+>
        <!ELEMENT mobil (#PCDATA)>
          <!ATTLIST mobil tipus (privat | feina) "privat">
        <!ELEMENT fix (#PCDATA)>
          <!ATTLIST fix tipus (privat | feina) "privat">
  <!ELEMENT factures (factura)+>
    <!ELEMENT factura (comprador, unitats+)>
      <!ATTLIST factura numero ID #REQUIRED>
      <!ELEMENT comprador EMPTY>
        <!ATTLIST comprador idClient IDREF #REQUIRED>
      <!ELEMENT unitats (#PCDATA)>
        <!ATTLIST unitats idVi IDREF #REQUIRED>

=== antonialoytorrens-DAW2018-2020/bodegaxml/factures2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE celler SYSTEM "factures.dtd">
  <celler>
    <productes>
      <producte id="b1" preu="10€">Botella de vi blanc 1L</producte>
      <producte id="b2" preu="20€">Botella de vi blanc 2L</producte>
      <producte id="b3" preu="28€">Botella de vi blanc 3L</producte>
      <producte id="b5" preu="40€">Botella de vi blanc 5L</producte>
      <producte id="n1" preu="5€">Botella de vi negre 1L</producte>
      <producte id="n2" preu="10€">Botella de vi negre 2L</producte>
      <producte id="n3" preu="14€">Botella de vi negre 3L</producte>
      <producte id="n5" preu="20€">Botella de vi negre 5L</producte>
      <producte id="r1" preu="7€">Botella de vi rosat 1L</producte>
      <producte id="r2" preu="14€">Botella de vi rosat 2L</producte>
      <producte id="r3" preu="20€">Botella de vi rosat 3L</producte>
      <producte id="r5" preu="25€">Botella de vi rosat 5L</producte>
    </productes>
    <clients>
      <client id="S41584222">
        <nom>Usama</nom>
        <llinatges>Ouekkai Nieto</llinatges>
        <contacte>
          <mobil tipus="privat">633539976</mobil>
          <fix tipus="feina">871911926</fix>
        </contacte>
      </client>
   </clients>
    <factures>
      <factura numero="f1">
        <comprador idClient="S41584222"/>
        <unitats idVi="b1">1</unitats>
        <unitats idVi="r3">5</unitats>
      </factura>
    </factures>
  </celler>
